// src/components/toolbar/InstrumentButton.tsx
import { globalState, NBSPlayer } from "@/NBSPlayer";
import { Instrument } from "@/NBS";
import { Component, RefObject, h, Fragment } from "preact";
import { SongEditor } from "../editor/editor";

import "./InstrumentButton.scss";
import { WebAudioNotePlayer } from "@/audio";

export interface InstrumentButtonProps {
    instrument: Instrument;
    id?: string;
}

export class InstrumentButton extends Component<InstrumentButtonProps> {
    private text() {
        const words = this.props.instrument.name.split(" ");

        if (words.length === 1) return this.props.instrument.name.substr(0, 2);
        else {
            return words
                .slice(0, 2)
                .map((i) => i[0])
                .join("");
        }
    }

    public activate() {
        const editor = globalState.value.editor;
        if (editor) editor.currentInstrument = this.props.instrument;

        WebAudioNotePlayer
            .playNote(editor?.currentKey || 0, this.props.instrument);
    }

    public render() {
        return (
            <a
                className="instrument-button"
                onClick={this.activate}
                value={(
                    globalState.value.editor?.currentInstrument ===
                    this.props.instrument
                ).toString()}
                title={`Set Instrument to ${this.props.instrument.name}`}
                id={this.props.id}
            >
                <div className="instrument-body">{this.text().toString()}</div>
            </a>
        );
    }
}

// src/components/toolbar/InstrumentButton.vue
<template>
    <a class="button" @click="activate" :value="active" :title="title">
        <div class="instrument-body">{{ text }}</div>
    </a>
</template>

<script>
import { Instrument } from "@/NBS";
import { SongEditor } from "@/components/editor/editor";
import { state } from "@/state";

export default {
    props: {
        instrument: Instrument,
        editor: SongEditor,
    },

    computed: {
        text() {
            const words = this.instrument.name.split(" ");
            if (words.length === 1) {
                return this.instrument.name.substr(0, 2);
            } else {
                return words
                    .slice(0, 2)
                    .map((i) => i[0])
                    .join("");
            }
        },
        active() {
            return this.editor.currentInstrument === this.instrument;
        },
        title() {
            return "Set Instrument to " + this.instrument.name;
        },
    },

    methods: {
        activate() {
            this.editor.currentInstrument = this.instrument;
            state.playNote(this.editor.currentKey, this.instrument);
        },
    },
};
</script>

<style scoped>
.button {
    position: relative;
}
.instrument-body {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
