// src/components/overlays/SettingsOverlay.tsx
import { globalState } from "@/NBSPlayer";
import { FunctionComponent, h, Fragment } from "preact";

export const SettingsOverlay: FunctionComponent<{
    keyOffset: number;
}> = (props) => {
    return (
        <div>
            <h3>Settings</h3>
            <div>
                <label>
                    Key Offset
                    <input type="number" value={props.keyOffset} />
                </label>
            </div>
            <button onClick={() => (globalState.value.showSettings = false)}>
                Close
            </button>
        </div>
    );
};

// src/components/overlays/SettingsOverlay.vue
<template>
    <div>
        <h3>Settings</h3>

        <div>
            <label>
                Key Offset
                <input type="number" v-model.number="options.keyOffset" />
            </label>
        </div>

        <button @click="hideSelf">Close</button>
    </div>
</template>

<script>
export default {
    inject: ["hide"],

    props: {
        options: Object,
    },

    methods: {
        hideSelf() {
            this.hide();
        },
    },
};
</script>

<style></style>
