// src/components/overlays/SongDetailsOverlay.vue
<template>
  <div class="details">
    <h2 class="title">{{ title }}</h2>
    <div v-if="song.author">
      Created by <b class="author">{{ song.author }}</b>
    </div>
    <div v-if="song.originalAuthor">
      Originally created by
      <b class="original-author">{{ song.originalAuthor }}</b>
    </div>

    <div>
      <textarea
        readonly
        class="description"
        v-if="song.description"
        v-model="song.description"
      ></textarea>
    </div>

    <div><button @click="hide">Dismiss</button></div>
  </div>
</template>

<script>
import * as NBS from "@/NBS.js";

export default {
  inject: ["hide"],
  props: {
    song: NBS.Song,
  },
  computed: {
    title() {
      return this.song.name || "Unnamed Song";
    },
  },
};
</script>

<style scoped>
.details {
  text-align: center;
}
.title,
.author,
.original-author {
  color: rgb(153, 0, 153);
  text-shadow: 2px 2px rgb(255, 203, 255);
  font-weight: bold;
}
.description {
  width: 100%;
}
</style>

// src/components/overlays/SongDetailsOverlay.tsx
import { Song } from "@/NBS";
import { globalState } from "@/NBSPlayer";
import { FunctionComponent, h, Fragment } from "preact";

import "./SongDetailsOverlay.scss";

export const SongDetailsOverlay: FunctionComponent<{
    song: Song;
}> = (props) => {
    return (
        <div className="details">
            <h2 className="title">
                {props.song.name.toString() || "Unnamed Song"}
            </h2>
            <div
                style={{
                    display: props.song.author ? "block" : "none",
                }}
            >
                Created by{" "}
                <b className="author">{props.song.author.toString()}</b>
            </div>
            <div
                style={{
                    display: props.song.originalAuthor ? "block" : "none",
                }}
            >
                Originally created by
                <b className="original-author">
                    {props.song.originalAuthor.toString()}
                </b>
            </div>

            <div>
                {props.song.description && (
                    <textarea
                        readOnly
                        className="description"
                        style={{
                            display: props.song.description ? "block" : "none",
                        }}
                        value={props.song.description}
                    />
                )}
            </div>

            <div>
                <button
                    onClick={() => (globalState.value.showSongDetails = false)}
                >
                    Dismiss
                </button>
            </div>
        </div>
    );
};
