// src/components/overlays/WelcomeOverlay.tsx
import { globalState, NBSPlayer } from "@/NBSPlayer";
import { Song } from "@/NBS";
import { loadFileState } from "@/state";
import { Component, h, Fragment } from "preact";
import { TargetedEvent } from "preact/compat";
// import { FontAwesomeIcon } from "../FontAwesomeIcon";

import "./WelcomeOverlay.scss";

export class WelcomeOverlay extends Component {
    private handleFileInput(event: TargetedEvent<HTMLInputElement, Event>) {
        const target = event.target as HTMLInputElement;

        if (!target.files || target.files?.length === 0) {
            return;
        }
        const file = target.files[0];

        loadFileState(file).then(() => this.hide());
    }

    private newSong() {
        globalState.value.song = Song.new();

        this.hide();
    }

    public hide() {
        globalState.value = { ...globalState.value, showWelcome: false };
    }

    public show() {
        globalState.value = { ...globalState.value, showWelcome: true };
    }

    public render() {
        return (
            <div className="flex flex-row">
                <div className="about section">
                    <h1>nbsplayer</h1>
                    <p>It's like Note Block Studio.</p>
                    <p>
                        Note sounds and textures are owned by Mojang. Not
                        approved by or associated with Mojang.
                    </p>
                </div>

                <div className="actions section">
                    <div className="load-song button flex flex-row flex-center">
                        {/* <FontAwesomeIcon
                            icon="folder-open"
                            fixed-width
                            size="2x"
                        /> */}
                        <div className="button-body">Load a song</div>
                        <input
                            className="file-input"
                            type="file"
                            accept=".nbs"
                            onChange={this.handleFileInput}
                        />
                    </div>
                    <div
                        className="new-song button flex flex-row flex-center"
                        onClick={this.newSong}
                    >
                        {/* <FontAwesomeIcon icon="file" fixed-width size="2x" /> */}
                        <div className="button-body">Create a new song</div>
                    </div>
                    <div
                        className="new-song button flex flex-row flex-center"
                        onClick={this.hide}
                        id="dismiss"
                    >
                        {/* <FontAwesomeIcon
                            icon="times-circle"
                            fixed-width
                            size="2x"
                        /> */}
                        <div className="button-body">Dismiss</div>
                    </div>
                </div>
            </div>
        );
    }
}

// src/components/overlays/WelcomeOverlay.vue
<template>
    <div class="flex flex-row">
        <div class="about section">
            <h1>nbsplayer</h1>
            <p>It's like Note Block Studio.</p>
            <p>
                Note sounds and textures are owned by Mojang. Not approved by or
                associated with Mojang.
            </p>
        </div>

        <div class="actions section">
            <div class="load-song button flex flex-row flex-center">
                <FontAwesomeIcon
                    icon="folder-open"
                    fixed-width
                    size="2x"
                ></FontAwesomeIcon>
                <div class="button-body">Load a song</div>
                <input
                    class="file-input"
                    type="file"
                    accept=".nbs"
                    @change="inputFile"
                />
            </div>
            <div
                class="new-song button flex flex-row flex-center"
                @click="newSong"
            >
                <FontAwesomeIcon
                    icon="file"
                    fixed-width
                    size="2x"
                ></FontAwesomeIcon>
                <div class="button-body">Create a new song</div>
            </div>
            <div
                class="new-song button flex flex-row flex-center"
                @click="hideSelf"
            >
                <FontAwesomeIcon
                    icon="times-circle"
                    fixed-width
                    size="2x"
                ></FontAwesomeIcon>
                <div class="button-body">Dismiss</div>
            </div>
        </div>
    </div>
</template>

<script>
import { FontAwesomeIcon } from "../FontAwesomeIcon";

import { Song } from "@/NBS";
import { state } from "@/state";

export default {
    inject: ["hide"],

    methods: {
        inputFile(event) {
            if (event.target.files.length === 0) {
                return;
            }
            const file = event.target.files[0];
            state.loadFile(file).then(() => this.hide());
        },

        newSong() {
            state.setSong(Song.new());
            this.hide();
        },

        hideSelf() {
            this.hide();
        },
    },

    components: {
        FontAwesomeIcon,
    },
};
</script>

<style scoped>
.section {
    padding: 0 10px;
    width: 50%;
}

p {
    font-size: 13px;
    margin: 3px 0;
}

.about {
    border-right: 1px solid #777;
    padding-right: 20px;
}
.about h1 {
    margin: 0;
}

.actions {
    font-size: 13px;
}

.button {
    padding: 10px;
    border-radius: 5px;
    min-width: 200px;
    /* makes the added border on hover not cause any size changes */
    border: 1px solid transparent;
}
.button:hover,
.button:active {
    border: 1px solid #777;
}
.button:active {
    background-image: linear-gradient(#dfdfdf, #cdcdcd);
}
.button-body {
    padding-left: 5px;
}

.load-song {
    position: relative;
}
.file-input {
    opacity: 0;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
</style>
