// src/components/layers/LayerList.vue
<template>
  <div class="layer-list">
    <time-box :song="song"></time-box>
    <layer-meta
      :layer="layer"
      :key="layer.id"
      v-for="layer in song.layers"
    ></layer-meta>
    <button @click="song.addLayer()" class="row">+ layer</button>
  </div>
</template>

<script>
import { Song } from "@/NBS.js";
import LayerMeta from "./LayerMeta.vue";
import TimeBox from "./TimeBox.vue";

export default {
  props: {
    song: Song,
  },
  components: {
    LayerMeta,
    TimeBox,
  },
};
</script>

<style scoped>
.row {
  height: 32px;
  width: 100%;
}
</style>

// src/components/layers/LayerList.tsx
import { Song } from "@/NBS";
import { FunctionComponent, h, Fragment } from "preact";
import { LayerMeta } from "./LayerMeta";
import { TimeBox } from "./TimeBox";

import "./LayerList.scss";
import { globalState } from "@/NBSPlayer";

export const LayerList: FunctionComponent<{ id?: string }> = (props) => {
    return (
        <div className="layer-list" id={props.id}>
            <TimeBox />

            {globalState.value.song.layers.map((layer) => (
                <LayerMeta layer={layer} key={layer.id} />
            ))}

            <button onClick={globalState.value.song.addLayer} className="row">
                + layer
            </button>
        </div>
    );
};
